/* eslint-disable */

import { GameData } from "./App/GameData";

export const testData: GameData = {
  found: true,
  uniqueId: "adfasdfas",
  state: "closed",
  type: "ai",
  map: "8p_nordwind\r",
  winCondition: "victory_point",
  left: {
    side: "allies",
    solo: [
      {
        members: [
          {
            ai: false,
            relicID: 3885757,
            name: "NIGHT",
            faction: "british",
            steamID: "76561198388327718",
            xp: 10158280,
            level: 185,
            country: "tr",
          },
        ],
        wins: 14,
        losses: 16,
        streak: 3,
        disputes: 0,
        drops: 0,
        rank: -1,
        ranktotal: 8133,
        ranklevel: 0,
        regionrank: -1,
        regionranktotal: 3170,
        lastmatchdate: 1610646515,
      },
      {
        members: [
          {
            ai: false,
            relicID: 3048480,
            name: "ESQ",
            faction: "aef",
            steamID: "76561198285169394",
            xp: 18785964,
            level: 300,
            country: "us",
          },
        ],
        wins: 2,
        losses: 1,
        streak: 1,
        disputes: 0,
        drops: 0,
        rank: -1,
        ranktotal: -1,
        ranklevel: -1,
        regionrank: -1,
        regionranktotal: -1,
        lastmatchdate: 1607220688,
      },
      {
        members: [
          {
            ai: false,
            relicID: 817924,
            name: "General of Stanasia",
            faction: "aef",
            steamID: "76561197991076804",
            xp: 13540488,
            level: 250,
            country: "ca",
          },
        ],
        wins: 4,
        losses: 1,
        streak: 2,
        disputes: 1,
        drops: 0,
        rank: -1,
        ranktotal: -1,
        ranklevel: -1,
        regionrank: -1,
        regionranktotal: -1,
        lastmatchdate: 1639329076,
      },
      {
        members: [
          {
            ai: false,
            relicID: 2184131,
            name: "John Wickedsick",
            faction: "british",
            steamID: "76561198141329771",
            xp: 18785964,
            level: 300,
            country: "de",
          },
        ],
        wins: 50,
        losses: 57,
        streak: 1,
        disputes: 1,
        drops: 0,
        rank: 753,
        ranktotal: 8133,
        ranklevel: 14,
        regionrank: 253,
        regionranktotal: 3285,
        lastmatchdate: 1646344374,
      },
    ],
    teams: [],
  },
  right: {
    side: "axis",
    solo: [
      {
        members: [
          {
            ai: true,
            relicID: -1,
            name: "Computer - Experte",
            faction: "german",
            steamID: "",
            xp: -1,
            level: -1,
            country: "",
          },
        ],
        wins: -1,
        losses: -1,
        streak: -1,
        disputes: -1,
        drops: -1,
        rank: -1,
        ranktotal: -1,
        ranklevel: -1,
        regionrank: -1,
        regionranktotal: -1,
        lastmatchdate: -1,
      },
      {
        members: [
          {
            ai: true,
            relicID: -2,
            name: "Computer - Experte",
            faction: "german",
            steamID: "",
            xp: -1,
            level: -1,
            country: "",
          },
        ],
        wins: -1,
        losses: -1,
        streak: -1,
        disputes: -1,
        drops: -1,
        rank: -1,
        ranktotal: -1,
        ranklevel: -1,
        regionrank: -1,
        regionranktotal: -1,
        lastmatchdate: -1,
      },
      {
        members: [
          {
            ai: true,
            relicID: -3,
            name: "Computer - Experte",
            faction: "german",
            steamID: "",
            xp: -1,
            level: -1,
            country: "",
          },
        ],
        wins: -1,
        losses: -1,
        streak: -1,
        disputes: -1,
        drops: -1,
        rank: -1,
        ranktotal: -1,
        ranklevel: -1,
        regionrank: -1,
        regionranktotal: -1,
        lastmatchdate: -1,
      },
      {
        members: [
          {
            ai: true,
            relicID: -4,
            name: "Computer - Experte",
            faction: "west_german",
            steamID: "",
            xp: -1,
            level: -1,
            country: "",
          },
        ],
        wins: -1,
        losses: -1,
        streak: -1,
        disputes: -1,
        drops: -1,
        rank: -1,
        ranktotal: -1,
        ranklevel: -1,
        regionrank: -1,
        regionranktotal: -1,
        lastmatchdate: -1,
      },
    ],
    teams: [],
  },
};
